const alojamientos = [
    { 
        tipo: 'departamento', 
        huespedes: 2, 
        precio: 100, 
        desayuno: true, 
        id: 1,
        imagen: '🏢',
        nombre: 'Luna Hermoso',
        telefono: '+54 9 123-4567890',
        descripcion: 'Acogedor departamento para 2 personas, ideal para parejas. Cuenta con desayuno incluido. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/luna-hermoso.html'
    },
    { 
        tipo: 'casa', 
        huespedes: 5, 
        precio: 200, 
        desayuno: false, 
        id: 2,
        imagen: '🏠',
        nombre: 'Sol Lindo',
        telefono: '+54 9 234-5678901',
        descripcion: 'Amplia casa con capacidad para 5 huéspedes. Perfecta para familias. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/sol-lindo.html'
    },
    { 
        tipo: 'quinta', 
        huespedes: 7, 
        precio: 350, 
        desayuno: true, 
        id: 3,
        imagen: '🏡',
        nombre: 'Estrella Brillante',
        telefono: '+54 9 345-6789012',
        descripcion: 'Espaciosa quinta para hasta 7 personas. Incluye desayuno. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/estrella-brillante.html'
    },
    { 
        tipo: 'cabaña', 
        huespedes: 4, 
        precio: 150, 
        desayuno: false, 
        id: 4,
        imagen: '🏚️',
        nombre: 'Montaña Sereno',
        telefono: '+54 9 456-7890123',
        descripcion: 'Encantadora cabaña en la montaña, para 4 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/montana-sereno.html'
    },
    { 
        tipo: 'departamento', 
        huespedes: 1, 
        precio: 80, 
        desayuno: true, 
        id: 5,
        imagen: '🏢',
        nombre: 'Río Radiante',
        telefono: '+54 9 567-8901234',
        descripcion: 'Departamento ideal para una persona, con desayuno incluido. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/rio-radiante.html'
    },
    { 
        tipo: 'casa', 
        huespedes: 6, 
        precio: 250, 
        desayuno: false, 
        id: 6,
        imagen: '🏠',
        nombre: 'Bosque Pacífico',
        telefono: '+54 9 678-9012345',
        descripcion: 'Casa espaciosa en un entorno tranquilo, capacidad para 6 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/bosque-pacifico.html'
    },
    { 
        tipo: 'quinta', 
        huespedes: 3, 
        precio: 300, 
        desayuno: true, 
        id: 7,
        imagen: '🏡',
        nombre: 'Mar Agradable',
        telefono: '+54 9 789-0123456',
        descripcion: 'Quinta con capacidad para 3 personas, incluye desayuno. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/mar-agradable.html'
    },
    { 
        tipo: 'cabaña', 
        huespedes: 5, 
        precio: 180, 
        desayuno: false, 
        id: 8,
        imagen: '🏚️',
        nombre: 'Playa Tranquilo',
        telefono: '+54 9 890-1234567',
        descripcion: 'Cabaña junto a la playa, para 5 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/playa-tranquilo.html'
    },
    { 
        tipo: 'departamento', 
        huespedes: 4, 
        precio: 120, 
        desayuno: true, 
        id: 9,
        imagen: '🏢',
        nombre: 'Campo Majestuoso',
        telefono: '+54 9 901-2345678',
        descripcion: 'Departamento amplio para 4 personas, incluye desayuno. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/campo-majestuoso.html'
    },
    { 
        tipo: 'casa', 
        huespedes: 7, 
        precio: 220, 
        desayuno: false, 
        id: 10,
        imagen: '🏠',
        nombre: 'Cielo Encantador',
        telefono: '+54 9 012-3456789',
        descripcion: 'Casa grande para 7 personas, perfecta para grupos. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/cielo-encantador.html'
    },
    { 
        tipo: 'quinta', 
        huespedes: 6, 
        precio: 400, 
        desayuno: true, 
        id: 11,
        imagen: '🏡',
        nombre: 'Sol Hermoso',
        telefono: '+54 9 123-4567890',
        descripcion: 'Quinta lujosa para 6 personas, con desayuno incluido. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/sol-hermoso.html'
    },
    { 
        tipo: 'departamento', 
        huespedes: 3, 
        precio: 110, 
        desayuno: true, 
        id: 12,
        imagen: '🏢',
        nombre: 'Lago Azul',
        telefono: '+54 9 234-5678901',
        descripcion: 'Departamento con vista al lago, para 3 personas. Incluye desayuno. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/lago-azul.html'
    },
    { 
        tipo: 'casa', 
        huespedes: 8, 
        precio: 280, 
        desayuno: false, 
        id: 13,
        imagen: '🏠',
        nombre: 'Jardín Encantado',
        telefono: '+54 9 345-6789012',
        descripcion: 'Casa amplia con jardín, para 8 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/jardin-encantado.html'
    },
    { 
        tipo: 'quinta', 
        huespedes: 10, 
        precio: 500, 
        desayuno: true, 
        id: 14,
        imagen: '🏡',
        nombre: 'Mansión Espléndida',
        telefono: '+54 9 456-7890123',
        descripcion: 'Lujosa mansión en una quinta, capacidad para 10 personas. Incluye desayuno. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/mansion-esplendida.html'
    },
    { 
        tipo: 'cabaña', 
        huespedes: 2, 
        precio: 130, 
        desayuno: false, 
        id: 15,
        imagen: '🏚️',
        nombre: 'Bosque Encantado',
        telefono: '+54 9 567-8901234',
        descripcion: 'Cabaña acogedora en el bosque, para 2 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/bosque-encantado.html'
    },
    { 
        tipo: 'departamento', 
        huespedes: 4, 
        precio: 140, 
        desayuno: true, 
        id: 16,
        imagen: '🏢',
        nombre: 'Río Sereno',
        telefono: '+54 9 678-9012345',
        descripcion: 'Departamento moderno junto al río, para 4 personas. Incluye desayuno. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/rio-sereno.html'
    },
    { 
        tipo: 'casa', 
        huespedes: 5, 
        precio: 210, 
        desayuno: false, 
        id: 17,
        imagen: '🏠',
        nombre: 'Sol Brillante',
        telefono: '+54 9 789-0123456',
        descripcion: 'Casa confortable para 5 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/sol-brillante.html'
    },
    { 
        tipo: 'quinta', 
        huespedes: 12, 
        precio: 600, 
        desayuno: true, 
        id: 18,
        imagen: '🏡',
        nombre: 'Quinta del Mar',
        telefono: '+54 9 890-1234567',
        descripcion: 'Quinta espaciosa para 12 personas, con desayuno incluido. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/quinta-del-mar.html'
    },
    { 
        tipo: 'cabaña', 
        huespedes: 3, 
        precio: 160, 
        desayuno: false, 
        id: 19,
        imagen: '🏚️',
        nombre: 'Montaña Azul',
        telefono: '+54 9 901-2345678',
        descripcion: 'Cabaña tranquila en la montaña, para 3 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/montana-azul.html'
    },
    { 
        tipo: 'departamento', 
        huespedes: 2, 
        precio: 90, 
        desayuno: true, 
        id: 20,
        imagen: '🏢',
        nombre: 'Cielo Radiante',
        telefono: '+54 9 012-3456789',
        descripcion: 'Departamento pequeño para 2 personas, con desayuno incluido. Aceptamos todos los medios de pago.',
        link: 'https://www.booking.com/hotel/ar/cielo-radiante.html'
    },
    { 
        tipo: 'casa', 
        huespedes: 4, 
        precio: 230, 
        desayuno: false, 
        id: 21,
        imagen: '🏠',
        nombre: 'Campo Tranquilo',
        telefono: '+54 9 123-4567890',
        descripcion: 'Casa rústica para 4 personas. Aceptamos solo efectivo.',
        link: 'https://www.booking.com/hotel/ar/campo-tranquilo.html'
    }
];
